// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
)

// Injectors from wire.go:

// BuildApp wires the server components using Google Wire.
func BuildApp(ctx context.Context) (*App, error) {
	config, err := provideConfig(ctx)
	if err != nil {
		return nil, err
	}
	logger := provideLogger(config)
	hub := provideHub()
	storage, err := provideStorage(ctx, config)
	if err != nil {
		return nil, err
	}
	gamifyService := provideService(hub, storage)
	handler := provideHandler(gamifyService, hub, config)
	server := provideServer(config, handler)
	app := &App{
		Config:  config,
		Logger:  logger,
		Hub:     hub,
		Service: gamifyService,
		Handler: handler,
		Server:  server,
	}
	return app, nil
}
